version: "3.8"

networks:
  attack-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

  log-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - bootstrap.memory_lock=true
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      log-net:
        ipv4_address: 192.168.200.10

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://192.168.200.10:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD="9jIAu_ubM7RxwgGfdPxq" # TODO Update if reboot
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5601
      - NODE_OPTIONS=--max-old-space-size=2048
      - XPACK_SECURITY_ENCRYPTIONKEY=changemechangemechangemechangeme
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=changemechangemechangemechangeme
      - XPACK_REPORTING_ENCRYPTIONKEY=changemechangemechangemechangeme
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      log-net:
        ipv4_address: 192.168.200.12

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    container_name: logstash
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/data:/usr/share/logstash/data
      - ./suricata/logs:/var/log/suricata:ro # le bug que j'avais ./suri  cata/...
    environment:
      - LS_JAVA_OPTS=-Xms1g -Xmx2g
    depends_on:
      - elasticsearch
    networks:
      log-net:
        ipv4_address: 192.168.200.11


  suricata:
    image: jasonish/suricata
    container_name: suricata
    network_mode: "container:victim"
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    volumes:
      - ./suricata:/etc/suricata
      - ./suricata/logs:/var/log/suricata
      - logstash_data:/usr/share/logstash/data
    command: >
      suricata -c /etc/suricata/suricata.yaml -i eth0
    depends_on:
      - victim

  victim:
   build:
     context: ./victim
     dockerfile: Dockerfile.victim
   container_name: victim
   tty: true
   stdin_open: true
   ports:
     - '3306:3306'
   dns:
     - 8.8.8.8
   networks:
     attack-net:
        ipv4_address: 192.168.100.20
     log-net:
        ipv4_address: 192.168.200.20

  kali:
    build:
      context: .
      dockerfile: Dokerfile.kali
    container_name: kali
    tty: true
    stdin_open: true
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    networks:
      attack-net:
        ipv4_address: 192.168.100.10

volumes:
  esdata:
  logstash_data:
