filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/suricata/eve.json
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      log_type: suricata

output.logstash:
  hosts: ["172.28.0.13:5044"]  # IP de logstash dans ton docker-compose